<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_Sum" Id="{892e2687-70d9-42b1-a064-73bb27ae28ab}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Sum
VAR_INPUT
	in1,in2:INT;
END_VAR

VAR_OUTPUT
	sum:INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[sum:=in1+in2;]]></ST>
    </Implementation>
    <LineIds Name="FB_Sum">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>